/****** Object:  Table [dbo].[workorderdowntimedetail]    Committed by VersionSQL https://www.versionsql.com ******/

/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2017 (14.0.1000)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[workorderdowntimedetail](
	[workorderno] [nvarchar](50) NULL,
	[downdate] [smalldatetime] NULL,
	[timefrom] [datetime] NULL,
	[timeto] [datetime] NULL,
	[employeeid] [nvarchar](50) NULL,
	[downid] [nvarchar](50) NULL,
	[totaldown] [float] NULL,
	[slno] [bigint] IDENTITY(1,1) NOT NULL,
	[AutoGenerated] [smallint] NULL,
 CONSTRAINT [PK_workorderdowntimedetail] PRIMARY KEY CLUSTERED 
(
	[slno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[workorderdowntimedetail] ADD  CONSTRAINT [DF_workorderdowntimedetail_workorderno]  DEFAULT ((0)) FOR [workorderno]
ALTER TABLE [dbo].[workorderdowntimedetail] ADD  CONSTRAINT [DF_workorderdowntimedetail_totaldown]  DEFAULT ((0)) FOR [totaldown]
ALTER TABLE [dbo].[workorderdowntimedetail] ADD  CONSTRAINT [DF_workorderdowntimedetail_AutoGenerated]  DEFAULT ((0)) FOR [AutoGenerated]