/****** Object:  Table [dbo].[workorderheader]    Committed by VersionSQL https://www.versionsql.com ******/

/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2017 (14.0.1000)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[workorderheader](
	[workorderno] [varchar](50) NOT NULL,
	[machineid] [varchar](50) NOT NULL,
	[customerid] [varchar](50) NOT NULL,
	[componentid] [varchar](50) NOT NULL,
	[wodate] [smalldatetime] NOT NULL,
	[operationno] [smallint] NOT NULL,
	[price] [float] NULL,
	[cycletime] [float] NULL,
	[closed] [smallint] NULL,
	[AutoGenerated] [smallint] NULL,
 CONSTRAINT [PK_workorderheader] PRIMARY KEY CLUSTERED 
(
	[workorderno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[workorderheader] ADD  CONSTRAINT [DF_workorderheader_price]  DEFAULT ((0)) FOR [price]
ALTER TABLE [dbo].[workorderheader] ADD  CONSTRAINT [DF_workorderheader_cycletime]  DEFAULT ((0)) FOR [cycletime]
ALTER TABLE [dbo].[workorderheader] ADD  CONSTRAINT [DF_workorderheader_closed]  DEFAULT ((0)) FOR [closed]
ALTER TABLE [dbo].[workorderheader] ADD  CONSTRAINT [DF_workorderheader_AutoGenerated]  DEFAULT ((0)) FOR [AutoGenerated]